# SPDX-FileCopyrightText: Copyright (c) 2020-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".gitmodules",
    ".latexmkrc",
    ".texsc",
    "_eolang/**",
    "iexec.ret",
    "**.jpg",
    "**.json",
    "**.md",
    "**.pdf",
    "**.png",
    "**.txt",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.gitmodules",
    "**/.latexmkrc",
    "**/.texsc",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.md",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/aspell.en.pws",
    "**/CITATION.cff",
    "**/CNAME",
    "**/DEPENDS.txt",
    "aspell.en.pws",
    "CITATION.cff",
    "DEPENDS.txt",
    "rc",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2020-2025 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
